In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

In [8]:
def simulador_credito_hipotecario(valor_financiado, tasa_mensual, plazo_meses):

    cuota_mensual = valor_financiado * (tasa_mensual * (1 + tasa_mensual) ** plazo_meses) / ((1 + tasa_mensual) ** plazo_meses - 1)
    return cuota_mensual


def simulador_leasing(valor_financiado, tasa_mensual, plazo_meses, opcion_compra):

    valor_residual = valor_inmueble * (opcion_compra / 100)
    cuota_mensual = (valor_financiado - valor_residual) * tasa_mensual * ((1 + tasa_mensual) ** plazo_meses) / ((1 + tasa_mensual) ** plazo_meses - 1)
    return cuota_mensual, valor_residual

# Función principal para el simulador
def simulador_inmobiliario(valor_inmueble, cuota_inicial, tasa_interes_anual, plazo_anios, modo='hipotecario', opc_compra=None):

    plazo_meses = plazo_anios * 12
    valor_financiado = valor_inmueble - cuota_inicial
    tasa_mensual = tasa_interes_anual / 12 / 100

    if modo == 'hipotecario':
        cuota = simulador_credito_hipotecario(valor_financiado, tasa_mensual, plazo_meses)
        print(f"Cuota mensual (Crédito Hipotecario): ${cuota:,.0f} COP")
    elif modo == 'leasing':
        if opc_compra is None:
            raise ValueError("Se debe especificar el % de opción de compra para el leasing.")
        cuota, valor_residual = simulador_leasing(valor_financiado, tasa_mensual, plazo_anios, plazo_meses)
        print(f"Cuota mensual (Leasing Habitacional): ${cuota:,.0f} COP")
        print(f"Valor residual al final del plazo: ${valor_residual:,.0f} COP")
    else:
        raise ValueError("Modo no reconocido. Use 'hipotecario' o 'leasing'.")


def generar_tabla_credito_hipotecario(valor_inmueble, cuota_inicial, tasa_interes_anual, plazo_anios):

    valor_financiado = valor_inmueble - cuota_inicial
    plazo_meses = plazo_anios * 12
    tasa_mensual = tasa_interes_anual / 12 / 100
    saldo_restante = valor_financiado

    datos = []
    cuota, valor_residual = simulador_leasing(valor_financiado, tasa_mensual, plazo_meses, opcion_compra=10)

    for mes in range (1, plazo_meses+1):
        interes_mes = saldo_restante * tasa_mensual
        capital_mes = cuota - interes_mes
        saldo_restante -= capital_mes
        datos.append({
                'Mes': mes,
                'Cuota': cuota,
                'Interés Pagado': interes_mes,
                'Capital Amortizado': capital_mes,
                'Saldo Restante': saldo_restante
            })

    return pd.DataFrame(datos)


valor_inmueble = 530_000_000  # Valor del inmueble
cuota_inicial = 50_000_000    # Cuota inicial
tasa_interes_anual = 12        # Tasa de interés anual en porcentaje
plazo_anios = 20               # Plazo en años


simulador_inmobiliario(valor_inmueble, cuota_inicial, tasa_interes_anual, plazo_anios, modo='hipotecario')

simulador_inmobiliario(valor_inmueble, cuota_inicial, tasa_interes_anual, plazo_anios, modo='leasing', opc_compra=10)

Cuota mensual (Crédito Hipotecario): $5,285,213 COP
Cuota mensual (Leasing Habitacional): $-43,888,929 COP
Valor residual al final del plazo: $1,272,000,000 COP

In [9]:
valor_inmueble = 530_000_000  # Valor del inmueble
cuota_inicial = 50_000_000    # Cuota inicial
tasa_interes_anual = 12        # Tasa de interés anual en porcentaje
plazo_anios = 20

tabla_amortizacion = generar_tabla_credito_hipotecario(valor_inmueble, cuota_inicial, tasa_interes_anual, plazo_anios)
tabla_amortizacion

     Mes         Cuota  Interés Pagado  Capital Amortizado  Saldo Restante
0      1 -4.388893e+07    4.800000e+06       -4.868893e+07    5.286889e+08
1      2 -4.388893e+07    5.286889e+06       -4.917582e+07    5.778647e+08
2      3 -4.388893e+07    5.778647e+06       -4.966758e+07    6.275323e+08
3      4 -4.388893e+07    6.275323e+06       -5.016425e+07    6.776966e+08
4      5 -4.388893e+07    6.776966e+06       -5.066590e+07    7.283625e+08
..   ...           ...             ...                 ...             ...
235  236 -4.388893e+07    4.607178e+08       -5.046068e+08    4.657639e+10
236  237 -4.388893e+07    4.657639e+08       -5.096528e+08    4.708604e+10
237  238 -4.388893e+07    4.708604e+08       -5.147494e+08    4.760079e+10
238  239 -4.388893e+07    4.760079e+08       -5.198968e+08    4.812069e+10
239  240 -4.388893e+07    4.812069e+08       -5.250958e+08    4.864578e+10

[240 rows x 5 columns]